config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get '/auth/github', as: :create_account
  get '/auth/github/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: :signout
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :provider, presence: true
  validates :uid, uniqueness: { scope: :username }
  validates :uid, presence: true
  validates :email, presence: true
  validates :username, presence: true
  validates :full_name, presence: true
  validates :avatar_url, presence: true
  validates :access_token, presence: true
  validates :account_created, presence: true

  def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

    find_by(provider: provider, uid: uid) || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create(
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      username: auth.info.nickname,
      full_name: auth.info.name,
      avatar_url: auth.info.image,
      access_token: auth.credentials.token, 
      account_created: auth.extra.raw_info.created_at
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?, :current_user

  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find(user_id) if user_id.present?
  end

  def signed_in?
    current_user.present?
  end

  def set_current_user(user)
    session[:user_id] = user.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = env['omniauth.auth']
    user = User.find_or_create_from_omniauth(auth)
    set_current_user(user)
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bootstrap/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand.visible-xs{href: "/"} GitSome
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.custom-brand
          %a{href: "/"} GitSome
        - if current_user
          %li.pull-right= link_to "Logout", signout_path
        - else
          %li.pull-right= link_to "Sign in with Github", create_account_path

app/views/home/index.html.haml
.row
  .col-md-3
    .portrait-placeholder
      %img{ src: "", class: "img-responsive img-thumbnail", id: "github-avatar" }
  .col-md-9
    %form{ role: "form", id: "onboard-form" }
      .form-group.form-group-lg#github-username-group
        %input{ type: "text", class: "form-control input-lg", placeholder: "Your Github username", id: "github-username" }
      .form-group.form-group-lg#gender-group
        %select{ class: "form-control input-lg", id: "gender-select" }
          %option{ value: "", "disabled" => "disabled", "selected" => "selected" } Select your gender
          %option{ value: "male", id: "gender-male" } Male
          %option{ value: "female", id: "gender-female" } Female
      .form-group.form-group-lg#match-group
        %select{ class: "form-control input-lg", id: "match-pref-select" }
          %option{ value: "", "disabled" => "disabled", "selected" => "selected" } Select your preference
          %option{ value: "men", id: "match-men" } Men
          %option{ value: "women", id: "match-women" } Women
    .form-errors
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no", name: "viewport"}
    %title= "GitSome" || yield(:title)
    = stylesheet_link_tag :application, :media => 'all'
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render 'bootstrap/navbar'
      = yield